services:
  app:
    environment:
      - FLASK_DEBUG=true
    volumes:
      - ./app:/app
      - ./volumes/db:/data/db
      - ./volumes/uploads:/data/uploads
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    volumes:
      - ./volumes/db:/data/db
    ports:
      - "${ADMINER_PORT:-8081}:8080"
